apiVersion: 1

groups:
  - orgId: 1
    name: MSP CPU Alerts
    folder: MSP Alerts
    interval: 1m

    rules:
      - uid: high_cpu_usage
        title: High CPU Usage
        condition: C

        data:
          - refId: A
            datasourceUid: ffm1y4x1ed2iod
            relativeTimeRange:
              from: 300
              to: 0

            model:
              expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
              refId: A
              instant: true
              datasource:
                type: prometheus
                uid: ffm1y4x1ed2iod

          - refId: C
            datasourceUid: __expr__
            model:
              type: threshold
              expression: A
              conditions:
                - evaluator:
                    type: gt
                    params:
                      - 85
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              refId: C

        noDataState: OK
        execErrState: Alerting
        for: 2m

        annotations:
          summary: "CPU usage alta"
          description: "CPU por encima del 85% en {{ $labels.instance }}"

        labels:
          severity: warning
          client: lab
          environment: production
          service: linux-host
