apiVersion: 1

groups:
  - orgId: 1
    name: MSP Container Alerts
    folder: MSP Alerts
    interval: 1m

    rules:
      - uid: container_down
        title: cAdvisor Down
        condition: C

        data:
          - refId: A
            datasourceUid: ffm1y4x1ed2iod
            relativeTimeRange:
              from: 300
              to: 0
            model:
              expr: min(up{job="cadvisor"}) == 0
              refId: A
              instant: true
              datasource:
                type: prometheus
                uid: ffm1y4x1ed2iod

          - refId: C
            datasourceUid: __expr__
            model:
              type: threshold
              expression: A
              conditions:
                - evaluator:
                    type: gt
                    params:
                      - 0
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              refId: C

        noDataState: OK
        execErrState: Alerting
        for: 1m

        annotations:
          summary: "cAdvisor caído"
          description: "cAdvisor no responde en {{ $labels.instance }}"

        labels:
          severity: critical
          client: lab
          environment: production
          service: docker
