apiVersion: 1

contactPoints:
  - orgId: 1
    name: MSP Telegram Alerts
    receivers:
      - uid: telegram_msp
        type: telegram
        settings:
          bottoken: "8871161034:AAGwB4fygZivGdhCi0hEJEW-5_EkfxPVP3k"
          chatid: "5937949811"
          message: |
            🚨 *MSP Alert*

            Cliente: {{ .CommonLabels.client }}
            Entorno: {{ .CommonLabels.environment }}
            Host: {{ .CommonLabels.instance }}
            Servicio: {{ .CommonLabels.service }}
            Severidad: {{ .CommonLabels.severity }}

            Estado: {{ .Status }}
            Alerta: {{ .CommonLabels.alertname }}

            Descripción:
            {{ .CommonAnnotations.description }}
